=== gate-tec/TRAMbio/resources/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="tram:components"
           xmlns="tram:components"
           xmlns:tram="tram:components"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
  <!-- Type Definitions -->
  <xs:simpleType name="id.type">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="key.type">
    <xs:restriction base="xs:float">
      <xs:pattern value="-INF|-?[0-9]+\.[0-9]+|0|[1-9][0-9]*" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="size.type">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="node.type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][0-9]{4}.[ A-Z0-9][A-Z0-9]{2}:[A-Z]+[A-Z0-9]{0,3}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="structure.type">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>
  <!-- Structure Definition -->
  <xs:element name="graph">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="components">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="component" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nodes">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="node.type" name="node" maxOccurs="unbounded" minOccurs="1"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="halo">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="node.type" name="node" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="id.type" name="id" use="required"/>
                  <xs:attribute type="size.type" name="size" use="required"/>
                  <xs:attribute type="structure.type" name="structure" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="size.type" name="size" use="required"/>
          </xs:complexType>
          <xs:unique name="components_component_id_unique">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                Ensures: uniqueness of id attributes of &lt;component&gt; children of this &lt;components&gt; element.
              </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="./tram:component"/>
            <xs:field xpath="@id"/>
          </xs:unique>
        </xs:element>
        <xs:element name="states">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="state" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="component" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="halo">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="node.type" name="node" maxOccurs="unbounded" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="components">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="component" maxOccurs="unbounded" minOccurs="1">
                                  <xs:complexType>
                                    <xs:attribute type="id.type" name="id" use="required"/>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="key.type" name="key" use="required"/>
                </xs:complexType>
                <xs:unique name="state_component_id_unique">
                  <xs:annotation>
                    <xs:documentation xml:lang="en">
                      Ensures: uniqueness of id attributes of &lt;component&gt; children in a &lt;components&gt; list of any &lt;component&gt; child of this &lt;state&gt; element.
                    </xs:documentation>
                  </xs:annotation>
                  <xs:selector xpath=".//tram:components/tram:component"/>
                  <xs:field xpath="@id"/>
                </xs:unique>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="key.type" name="key" use="optional"/>
          </xs:complexType>
          <xs:unique name="states_state_key_unique">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                Ensures: uniqueness of key attributes of &lt;state&gt; of this &lt;states&gt; element.
              </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="./tram:state"/>
            <xs:field xpath="@key"/>
          </xs:unique>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gate-tec/TRAMbio/tests/resources/xml/test_model_1_components.xml
<?xml version="1.0" encoding="UTF-8"?>
<graph xmlns="tram:components" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="tram:components https://raw.githubusercontent.com/gate-tec/TRAMbio/refs/heads/v0.0.0/resources/components.xsd">
    <components size="1">
        <component id="1" size="2">
            <nodes>
                <node>A0002-ASN:CG</node>
                <node>A0002-ASN:OD1</node>
            </nodes>
            <halo/>
        </component>
    </components>
    <states>
        <state key="-INF">
            <component>
                <halo>
                    <node>A0002-ASN:ND2</node>
                </halo>
                <components>
                    <component id="1"/>
                </components>
            </component>
        </state>
    </states>
</graph>
